Temporarily remove testing Java version in installation and launch
The test doesn't work with Java 10. The most portable way to test Java
version is by using Java property, not from command line output.

diff --git a/edu.rice.cs.hpc.viewer/scripts/install b/edu.rice.cs.hpc.viewer/scripts/install
--- a/edu.rice.cs.hpc.viewer/scripts/install
+++ b/edu.rice.cs.hpc.viewer/scripts/install
@@ -88,11 +88,11 @@ test "x$install_dir" != x || usage
 java_bindir=
 if test -n "$java_dir" ; then
     if test -f "${java_dir}/bin/java" ; then
-	java_bindir="${java_dir}/bin"
+	  java_bindir="${java_dir}/bin"
     elif test -f "${java_dir}/java" ; then
-	java_bindir="${java_dir}"
+	  java_bindir="${java_dir}"
     else
-	die "unable to find java in: $java_dir"
+	  die "unable to find java in: $java_dir"
     fi
     PATH="${java_bindir}:$PATH"
 fi
@@ -115,13 +115,13 @@ done
 
 if test "$force" = no ; then
     if test "x$java_version" = x ; then
-	die "unable to find program 'java' on your PATH"
+	  echo "unable to find program 'java' on your PATH"
     fi
-    minor=`expr "$java_version" : '[^.]*\.\([0-9]*\)'`
-    test "$minor" -ge 7 >/dev/null 2>&1
-    if test $? -ne 0 ; then
-	die "$java_version is too old, use Java 1.5 or later"
-    fi
+#    minor=`expr "$java_version" : '[^.]*\.\([0-9]*\)'`
+#    test "$minor" -ge 7 >/dev/null 2>&1
+#    if test $? -ne 0 ; then
+#	  echo "$java_version is too old, use Java 1.7 or later"
+#    fi
 fi
 
 #------------------------------------------------------------
